language: android

android:
   components:
   - tools
   - platform-tools
   - android-25
   - build-tools-25.0.0
   - extra

jdk: oraclejdk8

notifications:
  email: false

before_install:
   - touch local.properties

script:
  - ./gradlew install
